services:
    # GRIDS
    abbert_datagrid.datagrid:
        class: Abbert\DatagridBundle\Service\Datagrid
        arguments:
            - 'collectie met grids'
            - '@service_container'
            - '%abbert_datagrid.view.path%'
            - '@doctrine.orm.entity_manager'

    abbert_datagrid.datagrid_base: # TODO naam??
        class: Abbert\Datagrid\Datagrid
        calls:
            - [ setViewPath, [ '%abbert_datagrid.view.path%' ] ]